---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: hyprland-atomic

description: customized atomic hyprland image

base-image: ghcr.io/wayblueorg/hyprland-gdm

image-version: 42

modules:
  - type: rpm-ostree
    remove:
      - hyprland
      - xdg-desktop-portal-hyprland

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/dejan/lazygit/repo/fedora-%OS_VERSION%/dejan-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo

    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
        packages:
          - aquamarine
          - aylurs-gtk-shell
          - aylurs-gtk-shell2
          - cliphist
          - eww-git
          - hyprdim
          - hypridle
          - hyprland
          - hyprland-devel
          - hyprland-autoname-workspaces
          - hyprland-contrib
          - hyprland-plugins
          - hyprlang
          - hyprlock
          - hyprnome
          - hyprpanel
          - hyprpaper
          - hyprpicker
          - hyprpolkitagent
          - hyprshot
          - hyprsunset
          - hyprsysteminfo
          - hyprutils
          - mpvpaper
          - nwg-clipman
          - pyprland
          - satty
          - swaylock-effects
          - swww
          - uwsm
          - waypaper
          - xdg-desktop-portal-hyprland

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/dejan/lazygit/repo/fedora-%OS_VERSION%/dejan-lazygit-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo

    install:
      - hyprland
      - xdg-desktop-portal-hyprland

    # broadcom-wl dependency
      - rpmfusion-nonfree-release

    # logitech devices
      - solaar

    # Packages not found: hypridle, hyprland-qt-support, hyprlock, hyprpaper, hyprpicker, hyprpolkitagent
    # candy
      - hyprpaper
      - hyprpicker
      - hypridle
      - hyprcursor
      - hyprlock
      - hyprshot
      - satty
      - hyprpolkitagent
      - hyprland-qt-support

    # terminal
      - kitty

    # shell
      - bat
      - btop
      - fish
      - git-delta
      - highlight
      - lazygit
      - luarocks
      - neovim
      - pandoc

    # networking
      - samba
      - broadcom-wl

    # nautilus turtle plugin
      - dbus-python-devel
      - nautilus-python
      - python3-pygit2

    remove:
      - xfce-polkit
      - vim
      - thunar
      - thunar-volman
      - thunar-archive-plugin
      - swaylock
      - swayidle
      - swaybg
