---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: hyprland-atomic

description: customized atomic hyprland image

base-image: ghcr.io/wayblueorg/hyprland-gdm

image-version: 42

modules:
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/dejan/lazygit/repo/fedora-%OS_VERSION%/dejan-lazygit-fedora-%OS_VERSION%.repo
    install:
    # broadcom-wl dependency
      - rpmfusion-nonfree-release

    # logitech devices
      - solaar

    # candy
      - hyprpaper
      - hyprpicker
      - hypridle
      - hyprcursor
      - hyprlock
      - hyprpolkitagent
      - hyprland-qt-support

    # terminal
      - kitty

    # shell
      - bat
      - btop
      - fish
      - git-delta
      - highlight
      - lazygit
      - luarocks
      - neovim
      - pandoc

    # networking
      - samba
      - broadcom-wl

    # nautilus turtle plugin
      - dbus-python-devel
      - nautilus-python
      - python3-pygit2

    remove:
      - xorg-x11-server-Xwayland
      - xfce-polkit
      - vim
      - thunar
      - thunar-volman
      - thunar-archive-plugin
      - swaylock
      - swayidle
      - swaybg
